/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Root
         * @description 返回服务基本信息和可用接口。
         */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description 返回可用于前端状态栏的非敏感服务状态。
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/diagnose": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Diagnose
         * @description 执行同步诊断；默认仅返回最终报告以控制响应体大小。
         */
        post: operations["diagnose_diagnose_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/diagnose/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Diagnose Stream
         * @description 以 SSE 增量推送路由、Agent 与质量保障节点事件。
         */
        get: operations["diagnose_stream_diagnose_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memory/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Memory Stats
         * @description 保留旧接口，避免在前端切换期间破坏已有调用。
         */
        get: operations["memory_stats_memory_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/memory/clear": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Clear Memory
         * @description 保留旧接口，避免把未实现的清理动作伪装为成功。
         */
        post: operations["clear_memory_memory_clear_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sessions
         * @description 按更新时间倒序读取 Session 页面。
         */
        get: operations["list_sessions_api_v1_sessions_get"];
        put?: never;
        /**
         * Create Session
         * @description 创建 active Session；P2 仅承诺 Run 的持久化幂等语义。
         */
        post: operations["create_session_api_v1_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Session
         * @description 读取一个 Session。
         */
        get: operations["get_session_api_v1_sessions__session_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Session
         * @description 逻辑归档 Session；重复删除保持 204。
         */
        delete: operations["delete_session_api_v1_sessions__session_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Session
         * @description 更新标题或逻辑归档 Session；已归档记录不能重新激活。
         */
        patch: operations["update_session_api_v1_sessions__session_id__patch"];
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Messages
         * @description 按创建时间正序读取一个 Session 的消息。
         */
        get: operations["list_messages_api_v1_sessions__session_id__messages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions/{session_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Session Runs
         * @description 按创建时间倒序读取 Session 下的 Run，供刷新后恢复诊断工作区。
         */
        get: operations["list_session_runs_api_v1_sessions__session_id__runs_get"];
        put?: never;
        /**
         * Create Run
         * @description 原子受理 Run，成功受理后在 HTTP 响应完成后启动后台执行。
         */
        post: operations["create_run_api_v1_sessions__session_id__runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run
         * @description 读取 Run 与其成功后的结构化结果。
         */
        get: operations["get_run_api_v1_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Run Events
         * @description 按 sequence 正序读取已提交 RunEvent 页面。
         */
        get: operations["list_run_events_api_v1_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/runs/{run_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Run Events
         * @description 按持久化 sequence 重放事件；不产生即时或未提交 SSE 帧。
         */
        get: operations["stream_run_events_api_v1_runs__run_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AgentSummaryResource
         * @description Agent 运行摘要。
         */
        AgentSummaryResource: {
            /** Agent */
            agent: unknown;
            /** Status */
            status: unknown;
            /** Summary */
            summary: unknown;
            /** Duration Ms */
            duration_ms?: unknown;
        };
        /**
         * CreateRunRequest
         * @description 受理诊断 Run 的请求。
         */
        CreateRunRequest: {
            /** Query */
            query: string;
        };
        /**
         * CreateSessionRequest
         * @description 创建会话请求。
         */
        CreateSessionRequest: {
            /** Title */
            title: string;
            /** Environment Id */
            environment_id?: string | null;
            /** Incident Id */
            incident_id?: string | null;
        };
        /**
         * CursorPage
         * @description 固定排序列表的 cursor 分页信息。
         */
        CursorPage: {
            /** Next Cursor */
            next_cursor?: unknown;
            /** Has More */
            has_more: unknown;
        };
        /**
         * DiagnoseRequest
         * @description 同步诊断请求。
         */
        DiagnoseRequest: {
            /**
             * Query
             * @description 待诊断的运维问题
             */
            query: string;
            /**
             * Show Thinking
             * @description 是否返回诊断链路
             * @default false
             */
            show_thinking: boolean;
        };
        /**
         * DiagnoseResponse
         * @description 同步诊断响应。
         */
        DiagnoseResponse: {
            /** Result */
            result: string;
            /** Thinking */
            thinking?: string[] | null;
            /** Trace */
            trace?: components["schemas"]["TraceEvent"][] | null;
            /**
             * Strategy
             * @default
             */
            strategy: string;
        };
        /**
         * DiagnosisResultResource
         * @description 成功 Run 的已校验结构化结果。
         */
        DiagnosisResultResource: {
            /** Id */
            id: unknown;
            /** Run Id */
            run_id: unknown;
            /** Summary */
            summary: unknown;
            /** Severity */
            severity: unknown;
            /** Confidence */
            confidence: unknown;
            /** Root Causes */
            root_causes: unknown;
            /** Evidence */
            evidence: unknown;
            impact?: unknown;
            /** Recommendations */
            recommendations: unknown;
            /** Risks */
            risks: unknown;
            /** Requires Approval */
            requires_approval: unknown;
            /** Agent Summary */
            agent_summary: unknown;
            /** Report Markdown */
            report_markdown?: unknown;
            /** Created At */
            created_at: unknown;
        };
        /**
         * DiagnosisRunListResponse
         * @description 会话下 Run 的固定排序分页响应。
         */
        DiagnosisRunListResponse: {
            /** Items */
            items: unknown;
            page: unknown;
            meta: unknown;
        };
        /**
         * DiagnosisRunResource
         * @description 诊断 Run 资源。
         */
        DiagnosisRunResource: {
            /** Id */
            id: unknown;
            /** Session Id */
            session_id: unknown;
            /** Trace Id */
            trace_id: unknown;
            /** Input Message Id */
            input_message_id: unknown;
            /** Status */
            status: unknown;
            result?: unknown;
            error?: unknown;
            /** Created At */
            created_at: unknown;
            /** Started At */
            started_at?: unknown;
            /** Finished At */
            finished_at?: unknown;
        };
        /**
         * ErrorDetail
         * @description 参数校验失败时的单条字段错误。
         */
        ErrorDetail: {
            /** Location */
            location: (string | number)[];
            /** Message */
            message: string;
            /** Error Type */
            error_type: string;
        };
        /**
         * ErrorResponse
         * @description 统一错误响应。
         */
        ErrorResponse: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Details */
            details?: components["schemas"]["ErrorDetail"][] | null;
        };
        /**
         * EvidenceResource
         * @description 经安全审查的结构化证据。
         */
        EvidenceResource: {
            /** Id */
            id: unknown;
            /** Source Type */
            source_type: unknown;
            /** Source Name */
            source_name: unknown;
            /** Title */
            title: unknown;
            /** Summary */
            summary: unknown;
            /** Locator */
            locator?: unknown;
            /** Observed At */
            observed_at?: unknown;
            /** Attributes */
            attributes?: unknown;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description 服务健康检查响应。
         */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            /**
             * Mode
             * @enum {string}
             */
            mode: "mock" | "real";
            /** Model */
            model: string;
        };
        /**
         * ImpactResource
         * @description 影响范围。
         */
        ImpactResource: {
            /** Summary */
            summary: unknown;
            /** Affected Services */
            affected_services?: unknown;
            /** Affected Scope */
            affected_scope?: unknown;
        };
        JsonValue: unknown;
        /**
         * MemoryResponse
         * @description 保留的记忆接口响应。
         */
        MemoryResponse: {
            /** Status */
            status?: string | null;
            /** Message */
            message: string;
        };
        /**
         * MessageListResponse
         * @description 会话消息列表响应。
         */
        MessageListResponse: {
            /** Items */
            items: unknown;
            page: unknown;
            meta: unknown;
        };
        /**
         * MessageResource
         * @description 会话消息资源。
         */
        MessageResource: {
            /** Id */
            id: unknown;
            /** Session Id */
            session_id: unknown;
            /** Run Id */
            run_id?: unknown;
            /** Role */
            role: unknown;
            /** Content */
            content: unknown;
            /** Created At */
            created_at: unknown;
        };
        /**
         * RecommendationResource
         * @description 诊断建议。
         */
        RecommendationResource: {
            /** Id */
            id: unknown;
            /** Title */
            title: unknown;
            /** Description */
            description: unknown;
            /** Priority */
            priority: unknown;
            /** Risk Level */
            risk_level: unknown;
            /** Requires Approval */
            requires_approval: unknown;
            /** Evidence Ids */
            evidence_ids?: unknown;
        };
        /**
         * ResponseMeta
         * @description v1 HTTP 与 SSE 响应关联信息。
         */
        ResponseMeta: {
            /** Request Id */
            request_id: unknown;
            /** Trace Id */
            trace_id?: unknown;
        };
        /**
         * RiskResource
         * @description 诊断风险。
         */
        RiskResource: {
            /** Id */
            id: unknown;
            /** Level */
            level: unknown;
            /** Summary */
            summary: unknown;
            /** Mitigation */
            mitigation?: unknown;
        };
        /**
         * RootCauseResource
         * @description 结构化根因。
         */
        RootCauseResource: {
            /** Id */
            id: unknown;
            /** Title */
            title: unknown;
            /** Summary */
            summary: unknown;
            /** Confidence */
            confidence: unknown;
            /** Evidence Ids */
            evidence_ids?: unknown;
        };
        /**
         * RootResponse
         * @description 服务入口说明。
         */
        RootResponse: {
            /** Name */
            name: string;
            /** Version */
            version: string;
            /** Description */
            description: string;
            /** Endpoints */
            endpoints: {
                [key: string]: string;
            };
        };
        /**
         * RunErrorResource
         * @description 失败 Run 的安全错误。
         */
        RunErrorResource: {
            /** Code */
            code: unknown;
            /** Message */
            message: unknown;
        };
        /**
         * RunEventListResponse
         * @description Run 事件列表响应。
         */
        RunEventListResponse: {
            /** Items */
            items: unknown;
            page: unknown;
            meta: unknown;
        };
        /**
         * RunEventResource
         * @description 可持久化且可重放的 Run 事件。
         */
        RunEventResource: {
            /** Id */
            id: unknown;
            /** Run Id */
            run_id: unknown;
            /** Sequence */
            sequence: unknown;
            /** Type */
            type: unknown;
            /** Occurred At */
            occurred_at: unknown;
            /** Data */
            data: unknown;
        };
        /**
         * RunResponse
         * @description 单个 Run 响应。
         */
        RunResponse: {
            run: unknown;
            meta: unknown;
        };
        /**
         * SessionListResponse
         * @description 会话列表响应。
         */
        SessionListResponse: {
            /** Items */
            items: unknown;
            page: unknown;
            meta: unknown;
        };
        /**
         * SessionResource
         * @description 诊断会话资源。
         */
        SessionResource: {
            /** Id */
            id: unknown;
            /** Title */
            title: unknown;
            /** Status */
            status: unknown;
            /** Environment Id */
            environment_id?: unknown;
            /** Incident Id */
            incident_id?: unknown;
            /** Created At */
            created_at: unknown;
            /** Updated At */
            updated_at: unknown;
            /** Archived At */
            archived_at?: unknown;
        };
        /**
         * SessionResponse
         * @description 单个会话响应。
         */
        SessionResponse: {
            session: unknown;
            meta: unknown;
        };
        /**
         * SessionStatus
         * @description 诊断会话状态。
         * @enum {string}
         */
        SessionStatus: "active" | "archived";
        /**
         * TraceEvent
         * @description 诊断编排中的单条可视化事件。
         */
        TraceEvent: {
            /**
             * Type
             * @enum {string}
             */
            type: "route_decided" | "agent_start" | "agent_done" | "conflict_checked" | "debate_round" | "report" | "reflection";
            /** Node */
            node: string;
            /** Detail */
            detail: string;
            /**
             * Timestamp
             * @description UTC ISO 8601 时间戳
             */
            timestamp: string;
        };
        /**
         * UpdateSessionRequest
         * @description 更新会话标题或逻辑归档状态的请求。
         */
        UpdateSessionRequest: {
            /** Title */
            title?: string | null;
            /** Status */
            status?: ("active" | "archived") | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RootResponse"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    diagnose_diagnose_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiagnoseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagnoseResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal Server Error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    diagnose_stream_diagnose_stream_get: {
        parameters: {
            query: {
                query: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    memory_stats_memory_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryResponse"];
                };
            };
        };
    };
    clear_memory_memory_clear_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemoryResponse"];
                };
            };
        };
    };
    list_sessions_api_v1_sessions_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
                status?: components["schemas"]["SessionStatus"] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_session_api_v1_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_api_v1_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_session_api_v1_sessions__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_session_api_v1_sessions__session_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_messages_api_v1_sessions__session_id__messages_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_session_runs_api_v1_sessions__session_id__runs_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagnosisRunListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_run_api_v1_sessions__session_id__runs_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_v1_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_run_events_api_v1_runs__run_id__events_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunEventListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_run_events_api_v1_runs__run_id__stream_get: {
        parameters: {
            query?: {
                after_sequence?: string | null;
            };
            header?: {
                "Last-Event-ID"?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
